parameters:
    donjohn.media.type.class: Donjohn\MediaBundle\Form\Type\MediaType
    donjohn.media_collection.type.class: Donjohn\MediaBundle\Form\Type\MediaCollectionType
    donjohn.media_gallery.type.class: Donjohn\MediaBundle\Form\Type\MediaGalleryType

services:
    donjohn.media.type:
        class: "%donjohn.media.type.class%"
        arguments: ["@donjohn.media.provider.factory", "%donjohn.media.entity%"]
        tags:
            - { name: form.type }


    donjohn.media_collection.type:
        class: "%donjohn.media_collection.type.class%"
        arguments: ["%donjohn.media.entity%"]
        tags:
            - { name: form.type }

    donjohn.media_gallery.type:
        class: "%donjohn.media_gallery.type.class%"
        arguments: ["@doctrine.orm.default_entity_manager", "%donjohn.media.entity%"]
        tags:
            - { name: form.type }
